import 'package:get_it/get_it.dart';
import 'package:google_place/google_place.dart';
import 'package:cea_zed/app_constants.dart';
import 'package:cea_zed/domain/interface/address.dart';
import 'package:cea_zed/domain/interface/auth.dart';
import 'package:cea_zed/domain/interface/banner.dart';
import 'package:cea_zed/domain/interface/blog.dart';
import 'package:cea_zed/domain/interface/booking.dart';
import 'package:cea_zed/domain/interface/brands.dart';
import 'package:cea_zed/domain/interface/cart.dart';
import 'package:cea_zed/domain/interface/category.dart';
import 'package:cea_zed/domain/interface/chat.dart';
import 'package:cea_zed/domain/interface/form.dart';
import 'package:cea_zed/domain/interface/gallery.dart';
import 'package:cea_zed/domain/interface/master.dart';
import 'package:cea_zed/domain/interface/order.dart';
import 'package:cea_zed/domain/interface/parcel.dart';
import 'package:cea_zed/domain/interface/payments.dart';
import 'package:cea_zed/domain/interface/products.dart';
import 'package:cea_zed/domain/interface/review.dart';
import 'package:cea_zed/domain/interface/service.dart';
import 'package:cea_zed/domain/interface/settings.dart';
import 'package:cea_zed/domain/interface/shop.dart';
import 'package:cea_zed/domain/interface/user.dart';
import 'package:cea_zed/domain/service/http_service.dart';
import 'package:cea_zed/infrastructure/repository/address_repository.dart';
import 'package:cea_zed/infrastructure/repository/auth_repository.dart';
import 'package:cea_zed/infrastructure/repository/banners_repository.dart';
import 'package:cea_zed/infrastructure/repository/blogs_repository.dart';
import 'package:cea_zed/infrastructure/repository/booking_repository.dart';
import 'package:cea_zed/infrastructure/repository/brands_repository.dart';
import 'package:cea_zed/infrastructure/repository/cart_repository.dart';
import 'package:cea_zed/infrastructure/repository/categories_repository.dart';
import 'package:cea_zed/infrastructure/repository/chat_repository.dart';
import 'package:cea_zed/infrastructure/repository/form_repository.dart';
import 'package:cea_zed/infrastructure/repository/gallery_repository.dart';
import 'package:cea_zed/infrastructure/repository/master_repository.dart';
import 'package:cea_zed/infrastructure/repository/order_repository.dart';
import 'package:cea_zed/infrastructure/repository/parcel_repository.dart';
import 'package:cea_zed/infrastructure/repository/payments_repository.dart';
import 'package:cea_zed/infrastructure/repository/products_repository.dart';
import 'package:cea_zed/infrastructure/repository/review_repository.dart';
import 'package:cea_zed/infrastructure/repository/service_repository.dart';
import 'package:cea_zed/infrastructure/repository/settings_repository.dart';
import 'package:cea_zed/infrastructure/repository/shops_repository.dart';
import 'package:cea_zed/infrastructure/repository/user_repository.dart';

final GetIt getIt = GetIt.instance;

Future<void> setUpDependencies() async {
  getIt.registerLazySingleton<HttpService>(() => HttpService());
  getIt.registerSingleton<SettingsInterface>(SettingsRepository());
  getIt.registerSingleton<AuthInterface>(AuthRepository());
  getIt.registerSingleton<CategoryInterface>(CategoryRepository());
  getIt.registerSingleton<BannersInterface>(BannersRepository());
  getIt.registerSingleton<ProductsInterface>(ProductsRepository());
  getIt.registerSingleton<BlogInterface>(BlogsRepository());
  getIt.registerSingleton<ShopsInterface>(ShopsRepository());
  getIt.registerSingleton<BrandsInterface>(BrandsRepository());
  getIt.registerSingleton<GalleryInterface>(GalleryRepository());
  getIt.registerSingleton<UserInterface>(UserRepository());
  getIt.registerSingleton<ChatInterface>(ChatRepository());
  getIt.registerSingleton<AddressInterface>(AddressRepository());
  getIt.registerSingleton<CartInterface>(CartRepository());
  getIt.registerSingleton<ParcelInterface>(ParcelRepository());
  getIt.registerSingleton<ServiceInterface>(ServiceRepository());
  getIt.registerSingleton<GooglePlace>(GooglePlace(AppConstants.googleApiKey));
  getIt.registerSingleton<PaymentsInterface>(PaymentsRepository());
  getIt.registerSingleton<OrderInterface>(OrderRepository());
  getIt.registerSingleton<ReviewInterface>(ReviewRepository());
  getIt.registerSingleton<MasterInterface>(MasterRepository());
  getIt.registerSingleton<BookingInterface>(BookingRepository());
  getIt.registerSingleton<FormOptionsInterface>(FormOptionsRepository());
}

final settingsRepository = getIt.get<SettingsInterface>();
final dioHttp = getIt.get<HttpService>();
final authRepository = getIt.get<AuthInterface>();
final categoriesRepository = getIt.get<CategoryInterface>();
final bannersRepository = getIt.get<BannersInterface>();
final productsRepository = getIt.get<ProductsInterface>();
final blogsRepository = getIt.get<BlogInterface>();
final shopsRepository = getIt.get<ShopsInterface>();
final brandsRepository = getIt.get<BrandsInterface>();
final galleryRepository = getIt.get<GalleryInterface>();
final userRepository = getIt.get<UserInterface>();
final chatRepository = getIt.get<ChatInterface>();
final addressRepository = getIt.get<AddressInterface>();
final cartRepository = getIt.get<CartInterface>();
final serviceRepository = getIt.get<ServiceInterface>();
final googlePlace = getIt.get<GooglePlace>();
final paymentsRepository = getIt.get<PaymentsInterface>();
final ordersRepository = getIt.get<OrderInterface>();
final reviewRepository = getIt.get<ReviewInterface>();
final parcelRepository = getIt.get<ParcelInterface>();
final masterRepository = getIt.get<MasterInterface>();
final bookingRepository = getIt.get<BookingInterface>();
final formRepository = getIt.get<FormOptionsInterface>();
